spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/raymoe/spring-cloud-zuul-authentication.git
          search-paths: conf
          username: raymoe
          password: raymoe1989

server:
  port: 7001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/


