version: '3'
services:
  mysql_5.7:
    image: mysql:5.7
    container_name: mysql-5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql57:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root


volumes:
  mysql57:
    external: true